defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.zh-cn]
    languageName = "Chinese - Simplified (China)"
    weight = 1
    rtl = false
    title = "Cong"
    description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

  [languages.zh-cn.params]

  [languages.zh-cn.author]
    name = "Congo"
    image = "1006164.jpg"
    headline = "Not your ordinary theme!"
    bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
    links = [
      { twitter = "https://twitter.com/" },
      { facebook = "https://facebook.com/" },
      { linkedin = "https://linkedin.com/" },
      { youtube = "https://youtube.com/" },
    ]

    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post"
        weight = -3
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
        weight = -2
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = -1

[params]
colorScheme = "congo"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[params.homepage]
  layout = "profile"
  # showRecent = true

[params.article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = true
  showComments = true

[params.giscus]
enable = true

[params.custom]
js = []

[params.vercelAnalytics]
enable = false

[module]
[[module.imports]]
  path = 'github.com/jpanther/congo/v2'
