version: '3'

tasks:
  default:
    deps:
      - format:changed

  format:changed:
    cmds:
      - changed-files -f "(md|yml|html)$$" "prettier --single-quote --no-semi --trailing-comma es5 --write" | bash

  format:all:
    cmds:
      - prettier --single-quote --no-semi --trailing-comma es5 --write '{content,static,archetypes}/**/*.{md,yml,html}'
    sources:
      - '{content,static,archetypes}/**/*.{md,yml,html}'

  show-tags:
    cmds:
      - node hack/show-tags.js

  fixtab:
    cmds:
      - changed-files -f ".md$" "node hack/fixtab.js" | bash

  new-post:
    cmds:
      - ./hack/helper.sh {{.CLI_ARGS}}
