backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static' # Media files will be stored in the repo under static/img/uploads
public_folder: '/' # The src attribute for uploaded media will begin with /img/uploads

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog'
    folder: 'content/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'list',
          default: ['Default'],
        }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['Default'] }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
