name: Bump Themes

on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: bump themes
        run: |
          hugo mod get -u
          hugo mod tidy
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update themes'
