name: Compress Image

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Compress Images
        uses: zcong1993/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
