name: Compress Images
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '.github/workflows/image.yml'
jobs:
  build:
    name: calibreapp/image-actions
    if: "!contains(github.event.head_commit.message, 'Compressed Images')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Compressed Images
          branch: compress-image
          delete-branch: true
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
      - name: Merge Pr
        if: steps.pr.outputs.pull-request-url != ''
        run: >-
          gh pr merge compress-image -r -t 'chore: Compressed Images'
